### ISSUE TITLE
AWS IoT over Port 443

### ISSUE THREAD

**Issue by WolfWalter** [wolfSSL/wolfMQTT#103]
Hi,
to communicate with AWS IoT  over port 443 the ALPN ProtocolName  "x-amzn-mqtt-ca" has to be provided in the client hello. wolfssl supports that:
```
char alpn_list[] = "x-amzn-mqtt-ca";
wolfSSL_UseALPN(client->tls.ssl, alpn_list, strlen(alpn_list), WOLFSSL_ALPN_CONTINUE_ON_MISMATCH);
```

But there is no callback to execute that code after `wolfSSL_new()` and before`wolfSSL_connect()` in mqtt_socket.c -> MqttSocket_Connect(). Any suggestions how to accomplish that without modifying mqtt_socket.c?

Thanks!

**Comment by embhorn** [comment]
Hi Wolf,

You should be able to use the TLS callback in wolfMQTT to achieve this. In the AWS example we only create the context, but you could just as easily allocate the SSL structure as well (and call `wolfSSL_useALPN()`). Then in `MqttSocket_Connect()`, the default SSL allocation will be skipped because `client->tls.ssl == NULL` evaluates false.

Thanks,
Eric Blankenhorn
wolfSSL Support

**Comment by embhorn** [comment]
Hi Wolf,

Now I see what you mean. I will discuss with the team and report back. Probably we can reorder some of the init operations and make this work.

Thanks,
Eric Blankenhorn
wolfSSL Support

**Comment by embhorn** [comment]
There is a PR #104 that addresses this issue. I tested it with the AWS example using port 443 and calling `wolfSSL_UseALPN()` as you described and it works.

Thanks for bringing this to our attention, @WolfWalter !

**Comment by WolfWalter** [comment]
Thanks!
