### ISSUE TITLE
Big Endian in mqtt_types.h

### ISSUE THREAD

**Issue by nzamps** [wolfSSL/wolfMQTT#13]
Hey, 

Just wondering why Big Endian isn't allowed (via the check in mqtt_types.h)?  I'm using a few MIPS Big Endian devices and they work fine with the check commented out.  ?

**Comment by dgarske** [comment]
Hi Brian (nzamps),

That's great you are using wolfMQTT and had success using it in a big endian environment!

That check was added due to insufficient testing on big endian systems. The note says "#error Big Endian is not yet supported. Please contact us if you are interested in this feature."

I'll do some testing and see about removing this precautionary #error.

David Garske, wolfSSL
