### ISSUE TITLE
CPPFLAGS used for C sources

### ISSUE THREAD

**Issue by denravonska** [wolfSSL/wolfMQTT#72]
When configuring and adding additional CFLAGS they do not get included in the build command. Instead, you need to add them to CPPFLAGS in order to adapt the build.

**Comment by ejohnstown** [comment]
@dgarske, this is due to AX_HARDEN_CC_COMPILER_FLAGS stepping on CFLAGS. By default, AC_PROG_CC sets CFLAGS to "-g -O2". In wolfSSL's configure.ac we are using the line ${CFLAGS=""} to initialize CFLAGS to an empty string if not provided on the configure command line to stop AC_PROG_CC from doing that and so we can add those options later. Unfortunately, the harden macro has the line "CFLAGS=" to zap the variable. (wolfSSL's C_EXTRA_FLAGS was an attempt to work around this until I fixed the harden macro.)

IMO, the harden macro should be adding its flags to AM_CFLAGS, but I haven't spent the time to change that.

**Comment by dgarske** [comment]
Hi denravonska,

I've pushed an update to PR #71 to resolve this: https://github.com/wolfSSL/wolfMQTT/pull/71

Also in your description did you mean `CPPFLAGS`?

Thanks,
David Garske, wolfSSL

**Comment by denravonska** [comment]
@dgarske Ooops, I did. I'll try it out in the morning.

**Comment by denravonska** [comment]
That seems to be working, thanks.
